Issue 2
pechischev/task-manager pull request #9
Opened 2020-09-06 11:10 UTC by pechischev

2020-09-07 16:55 UTC, s3rious requested changes

2020-09-07 16:55 UTC, s3rious commented on client/src/states/store.ts
> +export const useAppDispatch = () => useDispatch<AppDispatch>();
Чёт это выглядит странновато, если честно.
Как минимум есть `store.dispatch`

2020-09-07 16:55 UTC, s3rious commented on client/src/components/TaskCard/TaskCard.tsx
>  import {ITaskCardProps} from './ITaskCardProps';
А зачем вытаскиват пропсы во внешний файлик? Я прям не вижу смысла.

Удобнее когда они объявлены прям тут, так и читать проще и импортить в другом месте так же просто, даже чуть явнее, мол «Дай мне пропсы _такого_ компонента»

2020-09-07 16:55 UTC, s3rious commented on client/src/components/TaskCard/TaskCard.tsx
>  import {ITaskCardProps} from './ITaskCardProps';
PS. Мне всегда казалось что префикс «I» в интерфейсах — это наследние джавы и сей, в общем и целом оно не очень требуется.

Я бы просто называл `TaskCardProps`

2020-09-07 16:55 UTC, s3rious commented on client/src/components/TaskCard/ITaskCardProps.ts
>  export interface ITaskCardProps extends HTMLAttributes<Element> {
Есть мнение, и я с ним солидарен, то type лучше чем interface :) 
https://medium.com/@martin_hotell/interface-vs-type-alias-in-typescript-2-7-2a8f1777af4c

Я бы везде херачил type

2020-09-07 16:55 UTC, s3rious commented on client/src/components/Layout/Layout.tsx
> +  <div className="layout">
А зачем со строчной?

2020-09-07 16:55 UTC, s3rious commented on client/src/components/AddTask/AddTask.tsx
> +export const AddTask: React.FunctionComponent<HTMLAttributes<HTMLButtonElement>> = (props) => (
Чёт я не очень думаю что `...props` — это хороший подход.

Мне кажется что описывать вполне себе конкретные пропы которые нужны и ничего больше — более правильнее и чуть безопаснее.

Тем более что я сонмневаюсь что нужно много специальных пропсов

2020-09-07 16:55 UTC, s3rious commented on client/src/app/useInitApp.ts
> +  useEffect(() => {
Ой, я оооооочень сомневаюсь что вот этот слой должен быть внутри реакта.

Мне кажется что это скорее initialState редьюсера.

2020-09-07 17:00 UTC, pechischev commented on client/src/states/store.ts
> +export const useAppDispatch = () => useDispatch<AppDispatch>();
так советуют на сайте redux

2020-09-07 17:01 UTC, pechischev commented on client/src/components/Layout/Layout.tsx
> +  <div className="layout">
так больше нравится, да и привычнее

2020-09-07 17:03 UTC, pechischev commented on client/src/app/useInitApp.ts
> +  useEffect(() => {
это на первое время, пока не прикручу хранение данных в бд

2020-09-07 17:04 UTC, pechischev commented on client/src/components/AddTask/AddTask.tsx
> +export const AddTask: React.FunctionComponent<HTMLAttributes<HTMLButtonElement>> = (props) => (
окей, будем описывать конкретные пропсы

2020-09-07 17:05 UTC, pechischev commented on client/src/components/TaskCard/TaskCard.tsx
>  import {ITaskCardProps} from './ITaskCardProps';
раньше в тайпскрипте предлагали писать c I, но ок, можно и без нее

2020-09-14 15:38 UTC, s3rious requested changes

2020-09-14 15:38 UTC, s3rious commented on client/src/app/forms/TaskForm/TaskForm.tsx
> +const TaskForm: FC<TaskFormProps> = ({ data = {}, onSubmit: handleSubmit }) => {
`FC` ж деприкейтед, нужно юзать `FunctionComponent`, не?
Там если в типы перейти то будет коммент.

Если нет, то тогда у нас на проекте разнобой и надо однообразно.

2020-09-14 15:51 UTC, pechischev commented on client/src/app/forms/TaskForm/TaskForm.tsx
> +const TaskForm: FC<TaskFormProps> = ({ data = {}, onSubmit: handleSubmit }) => {
не депрекейтед, просто сокращение от FunctionComponent

2020-09-14 15:51 UTC, merged